// Initialize Registrars and Providers
var REG_NONE = NewRegistrar('none');
var DSP_CLOUDFLARE = NewDnsProvider('cloudflare');

// Load the dynamic flat compilation file generated by GitHub Actions step
var parsedDomains = [];
try {
    // 👇 Changing this to './dist-domains.json' fixes execution directory pathing issues
    var contentStr = readfile('./dist-domains.json'); 
    parsedDomains = JSON.parse(contentStr);
} catch(e) {
    // Graceful fallback if file doesn't exist locally during offline editing
    parsedDomains = [];
}

// Configuration for your Master Apex Domain
D('code-space.me', REG_NONE, DnsProvider(DSP_CLOUDFLARE),
    A('@', '192.6.2.1'),     // Your personal landing page IP
    CNAME('www', '@'),       // Point www to apex

    // Inject user records smoothly using standard JavaScript map array syntax
    parsedDomains.map(function(d) {
        var subdomain = d.subdomain;
        var records = d.records;
        var commands = [];

        if (records.CNAME) {
            // Added CF_PROXY_OFF to make sure GitHub Pages handles the SSL handshake smoothly
            commands.push(CNAME(subdomain, records.CNAME, CF_PROXY_OFF)); 
        }
        if (records.A) {
            if (Array.isArray(records.A)) {
                records.A.forEach(function(ip) {
                    commands.push(A(subdomain, ip, CF_PROXY_OFF));
                });
            } else {
                commands.push(A(subdomain, records.A, CF_PROXY_OFF));
            }
        }
        return commands;
    })
);
