// Initialize Registrars and Providers
var REG_NONE = NewRegistrar('none');
var DSP_CLOUDFLARE = NewDnsProvider('cloudflare');

// Load the dynamic flat compilation file generated by GitHub Actions step
var parsedDomains = [];
try {
    var contentStr = readfile('./dist-domains.json'); 
    parsedDomains = JSON.parse(contentStr);
} catch(e) {
    parsedDomains = [];
}

// 🌐 Core Configuration for code-space Domain
D('code-space.me', REG_NONE, DnsProvider(DSP_CLOUDFLARE),
    // Point your main website root directly to GitHub Pages servers
    A('@', '185.199.108.153'),
    A('@', '185.199.109.153'),
    A('@', '185.199.110.153'),
    A('@', '185.199.111.153'),
    
    // Points www.code-space.me to your GitHub profile link
    CNAME('www', 's8rr.github.io.'), 

    // Inject user records smoothly using standard JavaScript map array syntax
    parsedDomains.map(function(d) {
        var subdomain = d.subdomain;
        var records = d.records;
        var commands = [];

        if (records.CNAME) {
            commands.push(CNAME(subdomain, records.CNAME, CF_PROXY_OFF)); 
        }
        if (records.A) {
            if (Array.isArray(records.A)) {
                records.A.forEach(function(ip) {
                    commands.push(A(subdomain, ip, CF_PROXY_OFF));
                });
            } else {
                commands.push(A(subdomain, records.A, CF_PROXY_OFF));
            }
        }
        return commands;
    })
);
