// Initialize Registrars and Providers
var REG_NONE = NewRegistrar('none');
var DSP_CLOUDFLARE = NewDnsProvider('cloudflare');

// Load the dynamic flat compilation file generated by GitHub Actions step 
var parsedDomains = [];
try {
    var contentStr = readfile('dist-domains.json');
    parsedDomains = JSON.parse(contentStr);
} catch(e) {
    // Graceful fallback if file doesn't exist locally during offline editing
    parsedDomains = [];
}

// Configuration for your Master Apex Domain
D('code-space.me', REG_NONE, DnsProvider(DSP_CLOUDFLARE),
    A('@', '192.0.2.1'),     // Your personal landing page IP
    CNAME('www', '@'),       // Point www to apex

    // Inject user records smoothly using standard JavaScript map array syntax
    parsedDomains.map(function(d) {
        var subdomain = d.subdomain;
        var records = d.records;
        var commands = [];

        if (records.CNAME) {
            commands.push(CNAME(subdomain, records.CNAME));
        }
        if (records.A) {
            if (Array.isArray(records.A)) {
                records.A.forEach(function(ip) {
                    commands.push(A(subdomain, ip));
                });
            } else {
                commands.push(A(subdomain, records.A));
            }
        }
        return commands;
    })
);
